# SPDX-License-Identifier: MIT

[package]
name = "rmexec"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "rmdb"

[dependencies]
rmcore = { path = "../rmcore" }
